# System Metrics Plugin Configuration
# Copy this file to your PLUGIN_DIR and reference it with `--trigger-arguments config_file_path=system_metrics_config_scheduler.toml`

########## Required Parameters ##########
# No required parameters - all have sensible defaults

########## Optional Parameters ##########

# Hostname to tag all metrics with
hostname = "localhost"  # e.g., "web-server-01", "db-primary"

# Control which metric types to collect
include_cpu = true      # Collect CPU usage, frequency, and per-core metrics
include_memory = true   # Collect memory and swap usage metrics  
include_disk = true     # Collect disk usage and I/O performance metrics
include_network = true  # Collect network interface statistics

# Error handling configuration
max_retries = 3         # Maximum retry attempts on collection failure

###### Example: Create Trigger Using This Config ######
# influxdb3 create trigger \
#   --database system_monitoring \
#   --plugin-filename system_metrics.py \
#   --trigger-spec "every:30s" \
#   --trigger-arguments config_file_path=system_metrics_config_scheduler.toml \
#   system_metrics_trigger