# MAD-Based Anomaly Detection Plugin Data Write Configuration Template
# Copy this file to your PLUGIN_DIR and reference it with
#   --trigger-arguments config_file_path=mad_anomaly_config_data_writes.toml


########## Required Parameters ##########
# InfluxDB measurement (table) to monitor for anomalies
measurement = "cpu"                   # e.g., "cpu", "temperature"

# MAD threshold conditions for anomaly detection
# Format: field:k:window_count:threshold
#   - field: numeric field name
#   - k: multiplier of MAD for cutoff
#   - window_count: number of recent points to compute median and MAD
#   - threshold: integer (count-based) or duration string (e.g., 2m) for duration-based triggering
# Example: temp:2:20:5@load:'3.5':10:2m
mad_thresholds = "temp:'2.5':20:5@load:'3.0':10:2m"

# Notification channels (dot-separated list)
senders = "slack.discord"            # e.g., "slack", "http.sms"



########## Optional Parameters ##########
# InfluxDB 3 API token (can also be set via INFLUXDB3_AUTH_TOKEN env var)
# influxdb3_auth_token = "YOUR_API_TOKEN"

# Maximum allowed flips in recent values before suppressing notifications
# state_change_count = 2                # default: 0 (disabled)

# Template for count-based notifications
# Variables: $table, $field, $threshold_count, $tags
# notification_count_text = "MAD count alert: $field on $table outlier for $threshold_count points. Tags: $tags"

# Template for duration-based notifications
# Variables: $table, $field, $threshold_time, $tags
# notification_time_text = "MAD duration alert: $field on $table outlier for $threshold_time. Tags: $tags"

# Custom URL path for Notification Sender plugin (default: "notify")
# notification_path = "custom/notify"

# Override InfluxDB port (default: 8181)
# port_override = 8182



########## Sender-Specific Settings ##########
# For each channel listed in senders, uncomment and configure the following parameters:

# --- Slack ---
# Webhook URL for Slack notifications (required)
# slack_webhook_url = "https://hooks.slack.com/services/XXX/YYY/ZZZ"
# Optional: Custom headers for Slack webhook (Base64-encoded JSON string)
# slack_headers = "eyJIb3N0IjogImV4YW1wbGUuY29tIn0="

# --- Discord ---
# Webhook URL for Discord notifications (required)
# discord_webhook_url = "https://discord.com/api/webhooks/AAA/BBB"
# Optional: Custom headers for Discord webhook (Base64-encoded JSON string)
# discord_headers = "eyJDb250ZW50VHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIn0="

# --- HTTP ---
# HTTP endpoint to send notifications (required)
# http_webhook_url = "https://example.com/webhook"
# Optional: Custom HTTP headers (Base64-encoded JSON string)
# http_headers = "eyJhdXRoIjogIkJlYXJlciBZT1VSX1RPS0VOIn0="

# --- SMS (Twilio) ---
# Twilio Account SID (required, or via TWILIO_SID env var)
# twilio_sid = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# Twilio Auth Token (required, or via TWILIO_TOKEN env var)
# twilio_token = "your_auth_token"
# Twilio sender number (required, format: +1234567890)
# twilio_from_number = "+1234567890"
# Recipient phone number (required, format: +0987654321)
# twilio_to_number = "+0987654321"

# --- WhatsApp (via Twilio) ---
# WhatsApp sender number (required, format: +1234567890)
# whatsapp_from_number = "+1234567890"
# WhatsApp recipient number (required, format: +0987654321)
# whatsapp_to_number = "+0987654321"



###### Example: Create Trigger Using This Config ######
# influxdb3 create trigger \
#   --database mydb \
#   --plugin-filename mad_check_plugin.py \
#   --trigger-spec "all_tables" \
#   --trigger-arguments config_file_path=mad_anomaly_config_data_writes.toml \
#   mad_anomaly_trigger
