# ADTK Anomaly Detection Plugin Scheduler Configuration Template
# Copy this file to your PLUGIN_DIR and reference it with
#   --trigger-arguments config_file_path=adtk_anomaly_config_scheduler.toml


########## Required Parameters ##########
# InfluxDB measurement (table) to query for anomalies
measurement = "cpu"                        # e.g., "cpu", "temperature"

# Numeric field to apply ADTK detectors on
field = "usage"                            # e.g., "usage", "value"

# ADTK detectors to use (dot-separated list)
detectors = "QuantileAD.LevelShiftAD"       # e.g., "InterQuartileRangeAD.ThresholdAD"

# Base64-encoded JSON string specifying detector parameters
# Format: {"DetectorName": {param1: value, ...}, ...}
detector_params = "eyJRZXF1YW50aWxlQURSIjogeyJsb3d..."  # decodes to {"QuantileAD": {"low_quantile": 0.05, "high_quantile": 0.95}, ...}

# Time window for analysis. Format: <number><unit>
# Units: s, min, h, d, w
window = "1h"                              # e.g., "15m", "24h"

# Notification channels (dot-separated list)
senders = "slack.discord"                  # e.g., "slack", "http.sms"



########## Optional Parameters ##########
# Minimum number of detectors that must agree on an anomaly
# min_consensus = "2"                         # default: 1

# Minimum duration an anomaly condition must persist before notifying
# min_condition_duration = "5m"           # e.g., "1m", "10m"

# InfluxDB 3 API token (or set via INFLUXDB3_AUTH_TOKEN env var)
# influxdb3_auth_token = "YOUR_API_TOKEN"

# Template for notification messages
# Variables: $table, $field, $value, $detectors, $timestamp, $tags
# notification_text = "Anomaly in $table.$field: value=$value at $timestamp detected by $detectors. Tags: $tags"

# URL path for Notification Sender plugin (default: "notify")
# notification_path = "notify"

# Override InfluxDB port for notifications (default: 8181)
# port_override = "8182"



########## Sender-Specific Settings ##########
# For each channel listed in senders, uncomment and configure the following parameters:

# --- Slack ---
# Webhook URL for Slack notifications (required)
# slack_webhook_url = "https://hooks.slack.com/services/XXX/YYY/ZZZ"
# Optional: Custom headers for Slack webhook (Base64-encoded JSON string)
# slack_headers = "eyJIb3N0IjogImV4YW1wbGUuY29tIn0="

# --- Discord ---
# Webhook URL for Discord notifications (required)
# discord_webhook_url = "https://discord.com/api/webhooks/AAA/BBB"
# Optional: Custom headers for Discord webhook (Base64-encoded JSON string)
# discord_headers = "eyJDb250ZW50VHlwZSI6ICJhcHBsaWNhdGlvbi9qc29uIn0="

# --- HTTP ---
# HTTP endpoint to send notifications (required)
# http_webhook_url = "https://example.com/webhook"
# Optional: Custom HTTP headers (Base64-encoded JSON string)
# http_headers = "eyJhdXRoIjogIkJlYXJlciBZT1VSX1RPS0VOIn0="

# --- SMS (Twilio) ---
# Twilio Account SID (required, or via TWILIO_SID env var)
# twilio_sid = "ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
# Twilio Auth Token (required, or via TWILIO_TOKEN env var)
# twilio_token = "your_auth_token"
# Twilio sender number (required, format: +1234567890)
# twilio_from_number = "+1234567890"
# Recipient phone number (required, format: +0987654321)
# twilio_to_number = "+0987654321"

# --- WhatsApp (via Twilio) ---
# WhatsApp sender number (required, format: +1234567890)
# whatsapp_from_number = "+1234567890"
# WhatsApp recipient number (required, format: +0987654321)
# whatsapp_to_number = "+0987654321"



###### Example: Create Trigger Using This Config ######
# influxdb3 create trigger \
#   --database mydb \
#   --plugin-filename adtk_anomaly_detection_plugin.py \
#   --trigger-spec "every:10m" \
#   --trigger-arguments config_file_path=adtk_anomaly_config_scheduler.toml \
#   adtk_anomaly_trigger
