version: "3.8"

services:
  fastapi:
    build: .
    container_name: new_fastapi_container
    ports:
      - "8001:8001"
    environment:
      - REDIS_HOST=host.docker.internal  
      - REDIS_PORT=6379